---------------------------------------------------------------------------
-- File name   : sin_rom.vhd
--
-- Project     : cushychicken/dds-engine
--
-- Description : ROM containing a quarter of a sine wave (0 < n < (pi/2))
--
-- Author(s)   : Nash Reilly (cushychicken@gmail.com)
--
-- Date        : August 13, 2021
--
-- Note(s)     : Sine coefficients generated by a helper script
--
----------------------------------------------------------------------------

library ieee;
  use ieee.std_logic_1164.all;
  use ieee.std_logic_unsigned.all;
  use ieee.std_logic_arith.all;

entity sin_rom is
  port (
    clock  : in    std_logic;
    addr  : in    std_logic_vector(13 downto 0);
    data : out   std_logic_vector(11 downto 0)
  );
end entity sin_rom;

architecture sin_rom_arch of sin_rom is

  -- Signals and constants here

  type rom_type is array (0 to 1023) of std_logic_vector(11 downto 0);

  constant ROM : rom_type := (
  -- Everything between these two comments is generated by Python
	{sintable}
  -- End Python generated section
  );

  memory : process(clock) 
  begin 
	  if (clock'event and clock='1') then
		  if (addr >= 0 and addr <= 1023) then
			  data <= ROM(conv_integer(address));
		  end if;
	  end if;
  end process memory;


begin

end architecture sin_rom_arch;
